/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, type ProblemDetails } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Provides a way to import data into the registry.
 */
export interface ImportRequestBuilder extends BaseRequestBuilder<ImportRequestBuilder> {
    /**
     * Imports registry data that was previously exported using the `/admin/export` operation.
     * @param body Binary request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @throws {ProblemDetails} error when the service returns a 409 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     post(body: ArrayBuffer | undefined, requestConfiguration?: RequestConfiguration<ImportRequestBuilderPostQueryParameters> | undefined) : Promise<void>;
    /**
     * Imports registry data that was previously exported using the `/admin/export` operation.
     * @param body Binary request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ArrayBuffer | undefined, requestConfiguration?: RequestConfiguration<ImportRequestBuilderPostQueryParameters> | undefined) : RequestInformation;
}
/**
 * Imports registry data that was previously exported using the `/admin/export` operation.
 */
export interface ImportRequestBuilderPostQueryParameters {
    /**
     * Query parameter indicating whether the registry must be empty before allowingdata to be imported.  Defaults to `true` if omitted.
     */
    requireEmptyRegistry?: boolean;
}
/**
 * Uri template for the request builder.
 */
export const ImportRequestBuilderUriTemplate = "{+baseurl}/admin/import{?requireEmptyRegistry*}";
/**
 * Metadata for all the requests in the request builder.
 */
export const ImportRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: ImportRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            409: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendNoResponseContent",
        requestBodyContentType: "application/zip",
        requestInformationContentSetMethod: "setStreamContent",
    },
};
/* tslint:enable */
/* eslint-enable */
