/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, createSystemInfoFromDiscriminatorValue, type ProblemDetails, type SystemInfo } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Retrieve system information
 */
export interface InfoRequestBuilder extends BaseRequestBuilder<InfoRequestBuilder> {
    /**
     * This operation retrieves information about the running registry system, such as the versionof the software and when it was built.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<SystemInfo>}
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<SystemInfo | undefined>;
    /**
     * This operation retrieves information about the running registry system, such as the versionof the software and when it was built.
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const InfoRequestBuilderUriTemplate = "{+baseurl}/system/info";
/**
 * Metadata for all the requests in the request builder.
 */
export const InfoRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: InfoRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createSystemInfoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
