/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithContentItemRequestBuilder, WithContentItemRequestBuilderNavigationMetadata, WithContentItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ids/contentIds
 */
export interface ContentIdsRequestBuilder extends BaseRequestBuilder<ContentIdsRequestBuilder> {
    /**
     * Access artifact content utilizing the unique content identifier for that content.
     * @param contentId Global identifier for a single artifact content.
     * @returns {WithContentItemRequestBuilder}
     */
     byContentId(contentId: number) : WithContentItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ContentIdsRequestBuilderUriTemplate = "{+baseurl}/ids/contentIds";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ContentIdsRequestBuilderNavigationMetadata: Record<Exclude<keyof ContentIdsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byContentId: {
        requestsMetadata: WithContentItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithContentItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["contentId"],
    },
};
/* tslint:enable */
/* eslint-enable */
