/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ConfigRequestBuilderNavigationMetadata, type ConfigRequestBuilder } from './config/index.js';
// @ts-ignore
import { ExportRequestBuilderRequestsMetadata, type ExportRequestBuilder } from './exportEscaped/index.js';
// @ts-ignore
import { ImportRequestBuilderRequestsMetadata, type ImportRequestBuilder } from './importEscaped/index.js';
// @ts-ignore
import { RoleMappingsRequestBuilderNavigationMetadata, RoleMappingsRequestBuilderRequestsMetadata, type RoleMappingsRequestBuilder } from './roleMappings/index.js';
// @ts-ignore
import { RulesRequestBuilderNavigationMetadata, RulesRequestBuilderRequestsMetadata, type RulesRequestBuilder } from './rules/index.js';
// @ts-ignore
import { SnapshotsRequestBuilderRequestsMetadata, type SnapshotsRequestBuilder } from './snapshots/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /admin
 */
export interface AdminRequestBuilder extends BaseRequestBuilder<AdminRequestBuilder> {
    /**
     * The config property
     */
    get config(): ConfigRequestBuilder;
    /**
     * Provides a way to export registry data.
     */
    get exportEscaped(): ExportRequestBuilder;
    /**
     * Provides a way to import data into the registry.
     */
    get importEscaped(): ImportRequestBuilder;
    /**
     * Collection to manage role mappings for authenticated principals
     */
    get roleMappings(): RoleMappingsRequestBuilder;
    /**
     * Manage the global rules that apply to all artifacts if not otherwise configured.
     */
    get rules(): RulesRequestBuilder;
    /**
     * Triggers a snapshot of the Registry storage. Only supported in KafkaSQL storage
     */
    get snapshots(): SnapshotsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const AdminRequestBuilderUriTemplate = "{+baseurl}/admin";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const AdminRequestBuilderNavigationMetadata: Record<Exclude<keyof AdminRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    config: {
        navigationMetadata: ConfigRequestBuilderNavigationMetadata,
    },
    exportEscaped: {
        requestsMetadata: ExportRequestBuilderRequestsMetadata,
    },
    importEscaped: {
        requestsMetadata: ImportRequestBuilderRequestsMetadata,
    },
    roleMappings: {
        requestsMetadata: RoleMappingsRequestBuilderRequestsMetadata,
        navigationMetadata: RoleMappingsRequestBuilderNavigationMetadata,
    },
    rules: {
        requestsMetadata: RulesRequestBuilderRequestsMetadata,
        navigationMetadata: RulesRequestBuilderNavigationMetadata,
    },
    snapshots: {
        requestsMetadata: SnapshotsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
