/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ContentHashesRequestBuilderNavigationMetadata, type ContentHashesRequestBuilder } from './contentHashes/index.js';
// @ts-ignore
import { ContentIdsRequestBuilderNavigationMetadata, type ContentIdsRequestBuilder } from './contentIds/index.js';
// @ts-ignore
import { GlobalIdsRequestBuilderNavigationMetadata, type GlobalIdsRequestBuilder } from './globalIds/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ids
 */
export interface IdsRequestBuilder extends BaseRequestBuilder<IdsRequestBuilder> {
    /**
     * The contentHashes property
     */
    get contentHashes(): ContentHashesRequestBuilder;
    /**
     * The contentIds property
     */
    get contentIds(): ContentIdsRequestBuilder;
    /**
     * The globalIds property
     */
    get globalIds(): GlobalIdsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const IdsRequestBuilderUriTemplate = "{+baseurl}/ids";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const IdsRequestBuilderNavigationMetadata: Record<Exclude<keyof IdsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    contentHashes: {
        navigationMetadata: ContentHashesRequestBuilderNavigationMetadata,
    },
    contentIds: {
        navigationMetadata: ContentIdsRequestBuilderNavigationMetadata,
    },
    globalIds: {
        navigationMetadata: GlobalIdsRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
