/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ArtifactTypesRequestBuilderRequestsMetadata, type ArtifactTypesRequestBuilder } from './artifactTypes/index.js';
// @ts-ignore
import { PropertiesRequestBuilderNavigationMetadata, PropertiesRequestBuilderRequestsMetadata, type PropertiesRequestBuilder } from './properties/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /admin/config
 */
export interface ConfigRequestBuilder extends BaseRequestBuilder<ConfigRequestBuilder> {
    /**
     * The list of artifact types supported by this instance of Registry.
     */
    get artifactTypes(): ArtifactTypesRequestBuilder;
    /**
     * Manage configuration properties.
     */
    get properties(): PropertiesRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const ConfigRequestBuilderUriTemplate = "{+baseurl}/admin/config";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ConfigRequestBuilderNavigationMetadata: Record<Exclude<keyof ConfigRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    artifactTypes: {
        requestsMetadata: ArtifactTypesRequestBuilderRequestsMetadata,
    },
    properties: {
        requestsMetadata: PropertiesRequestBuilderRequestsMetadata,
        navigationMetadata: PropertiesRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
