/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { ArtifactsRequestBuilderRequestsMetadata, type ArtifactsRequestBuilder } from './artifacts/index.js';
// @ts-ignore
import { GroupsRequestBuilderRequestsMetadata, type GroupsRequestBuilder } from './groups/index.js';
// @ts-ignore
import { type VersionsRequestBuilder, VersionsRequestBuilderRequestsMetadata } from './versions/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /search
 */
export interface SearchRequestBuilder extends BaseRequestBuilder<SearchRequestBuilder> {
    /**
     * Search for artifacts in the registry.
     */
    get artifacts(): ArtifactsRequestBuilder;
    /**
     * Search for groups in the registry.
     */
    get groups(): GroupsRequestBuilder;
    /**
     * Search for versions in the registry.
     */
    get versions(): VersionsRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SearchRequestBuilderUriTemplate = "{+baseurl}/search";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SearchRequestBuilderNavigationMetadata: Record<Exclude<keyof SearchRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    artifacts: {
        requestsMetadata: ArtifactsRequestBuilderRequestsMetadata,
    },
    groups: {
        requestsMetadata: GroupsRequestBuilderRequestsMetadata,
    },
    versions: {
        requestsMetadata: VersionsRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
