/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AdminRequestBuilderNavigationMetadata, type AdminRequestBuilder } from './admin/index.js';
// @ts-ignore
import { GroupsRequestBuilderNavigationMetadata, GroupsRequestBuilderRequestsMetadata, type GroupsRequestBuilder } from './groups/index.js';
// @ts-ignore
import { IdsRequestBuilderNavigationMetadata, type IdsRequestBuilder } from './ids/index.js';
// @ts-ignore
import { SearchRequestBuilderNavigationMetadata, type SearchRequestBuilder } from './search/index.js';
// @ts-ignore
import { SystemRequestBuilderNavigationMetadata, type SystemRequestBuilder } from './system/index.js';
// @ts-ignore
import { type UsersRequestBuilder, UsersRequestBuilderNavigationMetadata } from './users/index.js';
// @ts-ignore
import { apiClientProxifier, registerDefaultDeserializer, registerDefaultSerializer, type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * The main entry point of the SDK, exposes the configuration and the fluent API.
 */
export interface ApicurioRegistryClient extends BaseRequestBuilder<ApicurioRegistryClient> {
    /**
     * The admin property
     */
    get admin(): AdminRequestBuilder;
    /**
     * Collection of the groups in the registry.
     */
    get groups(): GroupsRequestBuilder;
    /**
     * The ids property
     */
    get ids(): IdsRequestBuilder;
    /**
     * The search property
     */
    get search(): SearchRequestBuilder;
    /**
     * The system property
     */
    get system(): SystemRequestBuilder;
    /**
     * The users property
     */
    get users(): UsersRequestBuilder;
}
/**
 * Instantiates a new {@link ApicurioRegistryClient} and sets the default values.
 * @param requestAdapter The request adapter to use to execute the requests.
 */
// @ts-ignore
export function createApicurioRegistryClient(requestAdapter: RequestAdapter) {
    const pathParameters: Record<string, unknown> = {
        "baseurl": requestAdapter.baseUrl,
    };
    return apiClientProxifier<ApicurioRegistryClient>(requestAdapter, pathParameters, ApicurioRegistryClientNavigationMetadata, undefined);
}
/**
 * Uri template for the request builder.
 */
export const ApicurioRegistryClientUriTemplate = "{+baseurl}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const ApicurioRegistryClientNavigationMetadata: Record<Exclude<keyof ApicurioRegistryClient, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    admin: {
        navigationMetadata: AdminRequestBuilderNavigationMetadata,
    },
    groups: {
        requestsMetadata: GroupsRequestBuilderRequestsMetadata,
        navigationMetadata: GroupsRequestBuilderNavigationMetadata,
    },
    ids: {
        navigationMetadata: IdsRequestBuilderNavigationMetadata,
    },
    search: {
        navigationMetadata: SearchRequestBuilderNavigationMetadata,
    },
    system: {
        navigationMetadata: SystemRequestBuilderNavigationMetadata,
    },
    users: {
        navigationMetadata: UsersRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
