/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithGlobalItemRequestBuilder, WithGlobalItemRequestBuilderNavigationMetadata, WithGlobalItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /ids/globalIds
 */
export interface GlobalIdsRequestBuilder extends BaseRequestBuilder<GlobalIdsRequestBuilder> {
    /**
     * Access artifact content utilizing an artifact version's globally unique identifier.
     * @param globalId Global identifier for an artifact version.
     * @returns {WithGlobalItemRequestBuilder}
     */
     byGlobalId(globalId: number) : WithGlobalItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const GlobalIdsRequestBuilderUriTemplate = "{+baseurl}/ids/globalIds";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const GlobalIdsRequestBuilderNavigationMetadata: Record<Exclude<keyof GlobalIdsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byGlobalId: {
        requestsMetadata: WithGlobalItemRequestBuilderRequestsMetadata,
        navigationMetadata: WithGlobalItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["globalId"],
    },
};
/* tslint:enable */
/* eslint-enable */
