name: Reproducer for Kiota issues

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        exec: [1, 2, 3, 4, 5, 6, 7, 8, 9 ,10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
      fail-fast: false
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Compile Integration Tests - Postgresql
        run: ./mvnw install -DskipTests -am --no-transfer-progress -Pintegration-tests -Pci -Premote-sql -pl integration-tests -Dmaven.javadoc.skip=true

      - name: Compile Integration Tests - Postgresql - Expected to fail
        run: ./mvnw -T 1.5C install -DskipTests -am --no-transfer-progress -Pintegration-tests -Pci -Premote-sql -pl integration-tests -Dmaven.javadoc.skip=true