/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createProblemDetailsFromDiscriminatorValue, HandleReferencesType, type ProblemDetails } from '../../../models/index.js';
// @ts-ignore
import { ReferencesRequestBuilderRequestsMetadata, type ReferencesRequestBuilder } from './references/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Access artifact content utilizing an artifact version's globally unique identifier.
 */
export interface WithGlobalItemRequestBuilder extends BaseRequestBuilder<WithGlobalItemRequestBuilder> {
    /**
     * The references property
     */
    get references(): ReferencesRequestBuilder;
    /**
     * Gets the content for an artifact version in the registry using its globally uniqueidentifier.This operation may fail for one of the following reasons:* No artifact version with this `globalId` exists (HTTP error `404`)* A server error occurred (HTTP error `500`)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     * @throws {ProblemDetails} error when the service returns a 404 status code
     * @throws {ProblemDetails} error when the service returns a 500 status code
     */
     get(requestConfiguration?: RequestConfiguration<WithGlobalItemRequestBuilderGetQueryParameters> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * Gets the content for an artifact version in the registry using its globally uniqueidentifier.This operation may fail for one of the following reasons:* No artifact version with this `globalId` exists (HTTP error `404`)* A server error occurred (HTTP error `500`)
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<WithGlobalItemRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
/**
 * Gets the content for an artifact version in the registry using its globally uniqueidentifier.This operation may fail for one of the following reasons:* No artifact version with this `globalId` exists (HTTP error `404`)* A server error occurred (HTTP error `500`)
 */
export interface WithGlobalItemRequestBuilderGetQueryParameters {
    /**
     * Allows the user to specify how references in the content should be treated.
     */
    references?: HandleReferencesType;
    /**
     * When set to `true`, the HTTP response will include a header named `X-Registry-ArtifactType`that contains the type of the artifact being returned.
     */
    returnArtifactType?: boolean;
}
/**
 * Uri template for the request builder.
 */
export const WithGlobalItemRequestBuilderUriTemplate = "{+baseurl}/ids/globalIds/{globalId}{?references*,returnArtifactType*}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithGlobalItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithGlobalItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    references: {
        requestsMetadata: ReferencesRequestBuilderRequestsMetadata,
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const WithGlobalItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithGlobalItemRequestBuilderUriTemplate,
        responseBodyContentType: "*/*, application/json",
        errorMappings: {
            404: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
            500: createProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
};
/* tslint:enable */
/* eslint-enable */
